name: Multiple Events Workflow
on:
  push:
    branches: [ '*' ]
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Toutes les 10 minutes
jobs:
  triggered_by:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered By
        run: echo "Le job a été déclenché par un événement de type ${{ github.event_name }}"
