name: Execute Script Workflow
on:
  push:
    branches: [ main ]
jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Execute Script
        run: python demo.py
